package com.welian.beans.cloudevent.project;


import java.util.Date;

/**
 * 从app_server查找过来的项目信息对象
 * Created by welian_gyc on 2017/5/5.
 */
public class ProjectsResp  {
    public Integer feed_status;
    public Integer feed_type;
    public Long feed_time;

    public String city_name;
    public Byte verify_status;
    public Date verify_time;
    public Byte financing_stage;
    public Date financing_endtime;

    public Byte team_scale;
    public String company;
    public Byte type;
    public Byte source;
    public Integer relation_id;

    public Integer industryId;

    public String industryName;

    public Integer city_id;
    public String welian_comment;
    public String advantage;
    public String solution;
    public String usage_scenario;
    public String operating_data;

    public Byte amount_unit;

    public Byte isopenbp;

    public Byte library_type;
    /**
     * 来源；0:微链；
     * 1：it桔子；
     * 2：运营上传；
     * 3:FA创建的项目；
     * 4:微链FA创建的项目，
     * 5：第三方渠道上传的项目，
     * 99:融资活动报名创建且找不到可关联的UID
     *
     * @param source
     */
    public Integer score;

    public String remark;


    public Date favorite_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.id
     *
     * @mbggenerated Tue Aug 18 10:18:41 CST 2015
     */
    public Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.uid
     *
     * @mbggenerated Tue Aug 18 10:18:41 CST 2015
     */
    public Integer uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.name
     *
     * @mbggenerated Tue Aug 18 10:18:41 CST 2015
     */
    public String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.intro
     *
     * @mbggenerated Tue Aug 18 10:18:41 CST 2015
     */
    public String intro;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.description
     *
     * @mbggenerated Tue Aug 18 10:18:41 CST 2015
     */
    public String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.website
     *
     * @mbggenerated Tue Aug 18 10:18:41 CST 2015
     */
    public String website;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.zan_count
     *
     * @mbggenerated Tue Aug 18 10:18:41 CST 2015
     */
    public Integer zan_count;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.comment_count
     *
     * @mbggenerated Tue Aug 18 10:18:41 CST 2015
     */
    public Integer comment_count;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.created
     *
     * @mbggenerated Tue Aug 18 10:18:41 CST 2015
     */
    public Date created;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.recommend
     *
     * @mbggenerated Tue Aug 18 10:18:41 CST 2015
     */
    public Integer recommend;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.recommend_time
     *
     * @mbggenerated Tue Aug 18 10:18:41 CST 2015
     */
    public Date recommend_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.updated
     *
     * @mbggenerated Tue Aug 18 10:18:41 CST 2015
     */
    public Date updated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.amount
     *
     * @mbggenerated Tue Aug 18 10:18:41 CST 2015
     */
    public Integer amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.stage
     *
     * @mbggenerated Tue Aug 18 10:18:41 CST 2015
     */
    public Integer stage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.share
     *
     * @mbggenerated Tue Aug 18 10:18:41 CST 2015
     */
    public Double share;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.financing_time
     *
     * @mbggenerated Tue Aug 18 10:18:41 CST 2015
     */
    public Date financing_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.status
     *
     * @mbggenerated Tue Aug 18 10:18:41 CST 2015
     */
    public Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.member_count
     *
     * @mbggenerated Tue Aug 18 10:18:41 CST 2015
     */
    public Integer member_count;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.deleted
     *
     * @mbggenerated Tue Aug 18 10:18:41 CST 2015
     */
    public Integer deleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.logo
     *
     * @mbggenerated Tue Aug 18 10:18:41 CST 2015
     */
    public String logo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.project_stage
     *
     * @mbggenerated Tue Aug 18 10:18:41 CST 2015
     */
    public Integer project_stage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.create_time
     *
     * @mbggenerated Tue Aug 18 10:18:41 CST 2015
     */
    public Long create_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.modify_time
     *
     * @mbggenerated Tue Aug 18 10:18:41 CST 2015
     */
    public Long modify_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.deliver_count
     *
     * @mbggenerated Tue Aug 18 10:18:41 CST 2015
     */
    public Integer deliver_count;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.refused_count
     *
     * @mbggenerated Tue Aug 18 10:18:41 CST 2015
     */
    public Integer refused_count;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.interview_count
     *
     * @mbggenerated Tue Aug 18 10:18:41 CST 2015
     */
    public Integer interview_count;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.financing
     *
     * @mbggenerated Tue Aug 18 10:18:41 CST 2015
     */
    public String financing;


    public Integer isZan;
}
