server:
  port: ${PORT:23550}

spring:
#db pool 以下配置根据环境更改
  datasource:
  #数据库名称
    db-name: welian_cloud_event
# REDIS (RedisProperties)
  redis:
    database: 52

# Kafka
  kafka:
    default:
      topic: ${spring.application.name}.test
    consumer:
      topics: ${spring.kafka.default.topic}

#自定义配置
cloudevent:
  #推广链接生成url时的前缀
    link_ticket_prefix: http://h5.wl.web/event/ticket/
    #兼容安卓3.3.1版本跳转不了票券问题
    link_ticket_compatibility_prefix: http://h5.wl.web/event/detail/ticket/
    link_jump_result_prefix: http://h5.wl.web/event/result/
    link_signup_prefix: http://h5.wl.web/sign/
    link_common_prefix: http://h5.wl.web/event/detail/
    link_form_prefix: http://h5.wl.web/event/signup/
    link_custom_prefix: http://h5.wl.web/event/custom/
    image_prefix: http://imgtest.welian.com/
    bp_prefix: http://restest.welian.com/
    #活动详情富文本
    event_content_url: http://h5.wl.web/event/richText/
  #传给短链生成服务，告诉其从哪地方来生成短链的，有个追踪
  url_req_source: cloud_event
  #机构的管理员能够修改机构的时间
  org_revise_day: 30
  #创建或修改推广链接的渠道信息时，需要过滤的渠道名称
  name_of_save_link_channel_filter: 来自微链
  #创建或修改推广链接的渠道信息时，需要的提示
  name_of_save_link_channel_filter_waining_tip: 敏感词汇，请更新渠道名称
  project_count_last_days: 1  # 统计项目数量定时任务,统计的天数,1表示1天前(昨天),2表示2天前(昨天,前天),以此类推,0的时候读取下面的值
  project_count_the_day: 2017-5-19 # 统计项目数量定时任务,统计特定日期的数据,可以为0
  #短信管理是否开启发送短信
  sms_send_flag: 0 # 0:开启，1：关闭
  sys_message_send_name: 活动小助手
  sys_message_send_logo: http://fed.welian.com/4_event/welianLogo.png
  default_admin_id: 133 #超级管理员默认id
  default_normal_user_id: 134 #普通用户默认id
  commodity_platform_id: 3 #商品服务平台id
  # solr的服务器地址
  solr_url: http://192.168.1.250:8983/solr/ik_event
  # 手续费
  poundage: 0.001
  # 项目默认logo
  project_default_logo: gger1462938439_120_120_5.png
client:
  app-server:
    url: http://welian.online:82
